spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: c2lsdmVyLW5pbmUtZGV2LXNucy1qd3Qtc2VjcmV0LWtleS1leGFtcGxlCg== # 사용자 제공 키 유지
  expiration: 86400000 # 1일 (24시간) - 토큰 만료 시간 추가